### ISSUE TITLE
Could not get yarn proxy to work

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-theme#11]
Fixed below (needed additional yarn build). However, why do I need docker when using remote molgenis instance?

How to reproduce (on Mac):
Follow manual until 'yarn proxy'

Expected:
Have things on localhost

Instead I got following console (it did not matter if docker was running or not)
![image](https://user-images.githubusercontent.com/120060/97464592-656ad180-1941-11eb-948c-0cc812d029dc.png)

**Comment by mswertz** [comment]
Fixed myself. Needed extra yarn build. However, why do I need to start docker when using remote master?

**Comment by jvanveen** [comment]
The nginx proxy runs in Docker. In a remote proxy setup (like against master.dev.molgenis.org), it is being used to replace the remote css files with the local ones, so you can observe scss changes directly.
