### ISSUE TITLE
cannot get 'yarn dev' to work on mac

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-theme#2]
What I did on my Mac (notice that I used modified package.json!)

git clone git@github.com:mswertz/molgenis-theme.git
cd molgenis-theme
yarn
cp docker/.env.default .env
yarn serve

Result:

![image](https://user-images.githubusercontent.com/120060/93628452-dd5ee700-f9e6-11ea-8bb8-d69c1747136c.png)

**Comment by connoratrug** [comment]
When i follow the install instruction en run ```yarn dev ```
I get an error saying: ```Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (88)```

**Comment by jvanveen** [comment]
@mswertz that should be solved by now. @connoratrug node-sass build depends on node-gyp and local utilities. Seems like for MacOS it needs xcode. We tried the dartsass package, but that doesn't solve this problem. Dartsass is about 4x slower than node-sass; even with the Fibers package (which relies on node-gyp as well). Closing this for now.
