### ISSUE TITLE
No bottom margin in form modal on user manager screen

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-theme#22]
In the user manager, in the Create User form, the Create button hugs the bottom of the modal.

![Schermafbeelding 2021-01-14 om 12 01 14](https://user-images.githubusercontent.com/1523838/104582589-5eaa4b80-5660-11eb-98ec-0a3a4ce05b99.png)

There used to be some space between them

<img width="917" alt="Schermafbeelding 2021-01-14 om 12 02 34" src="https://user-images.githubusercontent.com/1523838/104582646-6ff35800-5660-11eb-8bcd-65b53177d1a1.png">

**Comment by jvanveen** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=748518
