### ISSUE TITLE
Wizard previous / next buttons styling issues

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-theme#29]
* Disabled button text is light grey on white
* Restart button hugs the next step, I'd expect it to hug the previous step or be centered

![Schermafbeelding 2021-01-14 om 14 47 27](https://user-images.githubusercontent.com/1523838/104599043-983a8100-5677-11eb-9fd8-bd77247ed549.png)

<img width="1220" alt="Schermafbeelding 2021-01-14 om 14 49 41" src="https://user-images.githubusercontent.com/1523838/104599273-d899ff00-5677-11eb-8c74-16f5f6eb4554.png">

**Comment by MaxPostema** [comment]
#64 will not fix "Restart button hugs the next step, I'd expect it to hug the previous step or be centered" but do not think it's necessary for this release.
