### ISSUE TITLE
Mapping service image on button not visible 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-theme#32]
### How to Reproduce
Follow along the mapping service test plan to the step where you edit the height attr for the mapping_lifelines_test
( or edit any other attr in a mapping project)

### Expected behavior
the inspect detail button/link has a visible icon

### Observed behavior
the icon is not visible due to button styling 
<img width="1422" alt="Screenshot 2021-01-14 at 15 39 27" src="https://user-images.githubusercontent.com/47183404/104605528-ea32d500-567e-11eb-9a30-752f7ffd3db1.png">

**Comment by jvanveen** [comment]
Already fixed, checkout https://master.dev.molgenis.org/menu/dataintegration/mappingservice/attributeMapping?mappingProjectId=aaaac5y7z5wcshuda6wa2eqaae&target=c6_hernia1&source=c6_gender&targetAttribute=sortOrder
