### ISSUE TITLE
Data explorer copy dialog explanation text is light grey on light blue

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-theme#39]
![Schermafbeelding 2021-01-15 om 12 16 19](https://user-images.githubusercontent.com/1523838/104718694-916d4600-572b-11eb-8bd9-6117b12e188f.png)

before:
![Schermafbeelding 2021-01-15 om 12 17 05](https://user-images.githubusercontent.com/1523838/104718712-9cc07180-572b-11eb-822b-7709c6203245.png)

**Comment by jvanveen** [comment]
Please fix in molgenis template. Long descriptions should not be placed in the modal header
