### ISSUE TITLE
Filter wizard next button hugs the bottom of the modal

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-theme#43]
![Schermafbeelding 2021-01-15 om 13 15 12](https://user-images.githubusercontent.com/1523838/104726320-b796e400-5733-11eb-9da0-da6995cb173a.png)
![Schermafbeelding 2021-01-15 om 13 15 28](https://user-images.githubusercontent.com/1523838/104726367-c1b8e280-5733-11eb-8156-fbf112b77772.png)

**Comment by MaxPostema** [comment]
fixed by: https://github.com/molgenis/molgenis-theme/issues/22
