### ISSUE TITLE
Metadata manager missing margins between columns

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-theme#44]
![Schermafbeelding 2021-01-15 om 13 18 13](https://user-images.githubusercontent.com/1523838/104726577-23794c80-5734-11eb-8b55-771abf497c66.png)
![Schermafbeelding 2021-01-15 om 13 18 37](https://user-images.githubusercontent.com/1523838/104726611-32f89580-5734-11eb-950b-cef407a04091.png)

**Comment by jvanveen** [comment]
afaik: Restore gutter width Bootstrap
