### ISSUE TITLE
Questionnaires view button text barely visible

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-theme#47]
### How to Reproduce
Go to Questionaires

### Expected behavior
Text on button is clearly visible

### Observed behavior
Text on button is not very visible

**Comment by fdlk** [comment]
Duplicates #36

**Comment by jelmerveen** [comment]
![Screenshot 2021-01-15 at 13 44 48](https://user-images.githubusercontent.com/43730771/104728922-ec0c9f00-5737-11eb-9060-89df8b38a7ea.png)
