### ISSUE TITLE
Space around buttons missing

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-theme#49]
### How to Reproduce
Go to Filter wizard when using test Typetest
scroll down to the bottom

### Expected behavior
Next button is clearly visible with space around it

### Observed behavior
next button is next to bottom
![Screenshot 2021-01-15 at 12 35 38](https://user-images.githubusercontent.com/43730771/104728456-33466000-5737-11eb-94b0-0c5200294cb3.png)

**Comment by fdlk** [comment]
Duplicates #43
