### ISSUE TITLE
btn-secondary button text and icon barely visible

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-theme#50]
On SORTA job result page, the "back to tasks" button text and icon are barely visible

![Schermafbeelding 2021-01-15 om 14 20 18](https://user-images.githubusercontent.com/1523838/104732072-f2e9e080-573c-11eb-97e2-4f2ac2e77100.png)

![Schermafbeelding 2021-01-15 om 14 22 32](https://user-images.githubusercontent.com/1523838/104732183-20368e80-573d-11eb-9f46-dc86dd85b372.png)

**Comment by connoratrug** [comment]
closed by fix in molgenis: https://github.com/molgenis/molgenis/pull/9146
