### ISSUE TITLE
Installation steps only work for specific node version

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-theme#8]
### How to reproduce 
Follow install guide

### Expected 
Apps is installed without errors

### Actual 
if node version is less then 13, warring is show ```@molgenis/molgenis-theme@1.0.0: The engine "node" is incompatible with this module. Expected version ">=13.0.0". Got "12.18.0"```

 if node version is latest ( v15.0.1) the yarn command fails.

**Comment by connoratrug** [comment]
Solution for me was to use node v13.14.0

**Comment by jvanveen** [comment]
Related to node-sass issue on MacOS.

**Comment by connoratrug** [comment]
"_Related to node-sass issue on MacOS._" its still in issue, even if its a mac only issue
